//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apps.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SysModule
    {
        public string ID { get; set; }
        public string Name { get; set; }
        public string EnglishName { get; set; }
        public string ParentID { get; set; }
        public string Url { get; set; }
        public string Iconic { get; set; }
        public Nullable<long> Sort { get; set; }
        public string Remark { get; set; }
        public Nullable<bool> State { get; set; }
        public string CreatePerson { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<bool> IsLast { get; set; }
        public System.DateTime Version { get; set; }
    }
}
